const ADD_MODULE = 'ADD_MODULE'
const UPDATE_MODULE = 'UPDATE_MODULE'
const DELETE_MODULE = 'DELETE_MODULE'
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
const SWITCH_CHAPTER="SWITCH_CHAPTER"


export default {TOGGLE_SIDEBAR,ADD_MODULE, UPDATE_MODULE ,DELETE_MODULE,SWITCH_CHAPTER };
