const ADD_MODULE = 'ADD_MODULE'
const UPDATE_MODULE = 'UPDATE_MODULE'
const DELETE_MODULE = 'DELETE_MODULE'
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
const SWITCH_CHAPTER="SWITCH_CHAPTER"
const GET_MODULES="GET_MODULES"
const GET_CHAPTERS="GET_CHAPTERS"
const GET_WIDGETS="GET_WIDGETS"
const COURSE_LOAD_FAILED='COURSE_LOAD_FAILED'
const COURSE_LOAD_SUCCESS='COURSE_LOAD_SUCCESS'
const COURSE_LOAD_START='COURSE_LOAD_START'
const MODULES_LOAD_START="MODULES_LOAD_START"
const MODULES_LOAD_SUCCESS="MODULES_LOAD_SUCCESS"
const MODULES_LOAD_FAILED="MODULES_LOAD_FAILED"
const MODULE_MAKE_ACTIVE="MODULE_MAKE_ACTIVE"
const CHAPTERS_LOAD_START="CHAPTERS_LOAD_START"
const CHAPTERS_LOAD_SUCCESS="CHAPTERS_LOAD_SUCCESS"
const CHAPTERS_LOAD_FAILED="CHAPTERS_LOAD_FAILED"
const MODULE_SELECTED ="MODULE_SELECTED"
const CHAPTER_MAKE_ACTIVE = "CHAPTER_MAKE_ACTIVE"
const CHAPTER_SELECTED = "CHAPTER_SELECTED"
const WIDGETS_LOAD_SUCCESS ="WIDGETS_LOAD_SUCCESS"
const WIDGETS_LOAD_FAILED = "WIDGETS_LOAD_FAILED"
const WIDGETS_LOAD_START = "WIDGETS_LOAD_START"
const WIDGET_SELECTED = "WIDGET_SELECTED"
const OPEN_WIDGET_FORM = "OPEN_WIDGET_FORM"
const CLOSE_WIDGET_FORM ="CLOSE_WIDGET_FORM"
const USER_LOAD_SUCCESS="USER_LOAD_SUCCESS"
const USER_LOAD_FAILED="USER_LOAD_FAILED"
const USER_LOAD_START="USER_LOAD_START"
const USER_LOGOUT="USER_LOGOUT"
const COURSE_LIST_LOAD_START="COURSE_LIST_LOAD_START"
const COURSE_LIST_LOAD_FAILED="COURSE_LIST_LOAD_FAILED"
const COURSE_LIST_LOAD_SUCCESS="COURSE_LIST_LOAD_SUCCESS"
const COURSE_MAKE_ACTIVE="COURSE_MAKE_ACTIVE"
const SWITCH_PAGE="SWITCH_PAGE"
export default {TOGGLE_SIDEBAR,ADD_MODULE, UPDATE_MODULE ,
                DELETE_MODULE,SWITCH_CHAPTER,
                GET_MODULES,GET_CHAPTERS,GET_WIDGETS,
                COURSE_LOAD_FAILED,COURSE_LOAD_SUCCESS,
                COURSE_LOAD_START,MODULES_LOAD_START,
                MODULES_LOAD_SUCCESS,MODULES_LOAD_FAILED,
                MODULE_MAKE_ACTIVE,CHAPTERS_LOAD_START,
                CHAPTERS_LOAD_SUCCESS,CHAPTERS_LOAD_FAILED,
                MODULE_SELECTED, CHAPTER_MAKE_ACTIVE, CHAPTER_SELECTED,
                WIDGETS_LOAD_SUCCESS,WIDGETS_LOAD_FAILED,
                WIDGETS_LOAD_START,WIDGET_SELECTED,OPEN_WIDGET_FORM,
                CLOSE_WIDGET_FORM,USER_LOAD_SUCCESS,USER_LOAD_FAILED
                ,USER_LOAD_START,USER_LOGOUT,
                COURSE_LIST_LOAD_START,COURSE_LIST_LOAD_FAILED,
                COURSE_LIST_LOAD_SUCCESS,COURSE_MAKE_ACTIVE,SWITCH_PAGE};
