const ADD_MODULE = 'ADD_MODULE'
const UPDATE_MODULE = 'UPDATE_MODULE'
const DELETE_MODULE = 'DELETE_MODULE'
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
const SWITCH_CHAPTER="SWITCH_CHAPTER"
const GET_MODULES="GET_MODULES"
const GET_CHAPTERS="GET_CHAPTERS"
const GET_WIDGETS="GET_WIDGETS"
const COURSE_LOAD_FAILED='COURSE_LOAD_FAILED'
const COURSE_LOAD_SUCCESS='COURSE_LOAD_SUCCESS'
const COURSE_LOAD_START='COURSE_LOAD_START'
export default {TOGGLE_SIDEBAR,ADD_MODULE, UPDATE_MODULE ,
                DELETE_MODULE,SWITCH_CHAPTER,
                GET_MODULES,GET_CHAPTERS,GET_WIDGETS,
                COURSE_LOAD_FAILED,COURSE_LOAD_SUCCESS,
                COURSE_LOAD_START};
